const DAYS=['Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday'];
const TIMES=['08:30-10:00','10:00-11:30','11:30-13:00','13:00-14:30','14:30-16:00'];
const LEVELS=['First Year Preparatory Cycle','Second Year Preparatory Cycle'];
const SEMESTERS={"First Year Preparatory Cycle":['Semester 1','Semester 2'],"Second Year Preparatory Cycle":['Semester 3','Semester 4']};
const ALL_LEVELS='All academic levels', ALL_SEMESTERS='All semesters';
const DATA_VERSION=window.MASTER_DATA.dataVersion||'master';
const KEY=`prep-cycle-schedule-${DATA_VERSION}`, RECORD_KEY='prep-cycle-records-v1';
let sessions=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(window.MASTER_DATA.sessions);
let records=JSON.parse(localStorage.getItem(RECORD_KEY)||'{"coordination":[],"scientific":[],"competition":[],"studentRepresentatives":[],"studentAbsences":[]}');
let scheduleView='days';
let serverMode=false,serverSaveTimer=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const unique=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b));
const APP_BASE=new URL('./',document.querySelector('script[src$="app.js"]').src);
const apiUrl=path=>new URL(String(path).replace(/^\/+/,''),APP_BASE).toString();
const VIEW_NAMES=['timetable','hours','studentRepresentatives','studentAbsences','teachers','coordination','scientific','competition'];
const ALL_DEPARTMENTS='All departments',ALL_HOURS_SEMESTERS='All populated semesters';
const departmentOf=session=>session.department||'Preparatory Cycle';
let TEACHERS=unique([...(window.ALL_TEACHERS||[]),...window.MASTER_DATA.sessions.map(s=>s.professor)]);
const MODULE_PALETTE=['#B055A8','#9B5D52','#7257C5','#3E7446','#197BC3','#278F70','#D45652','#D17A2F','#3F75A6','#8B62B5','#2F8F9D','#C24E7A','#5D7E3B','#A65D32','#4768B1','#7B6848','#3C9187','#B94B5C','#6E5AA8','#3E7E60','#A86091','#526F9A','#91733F','#417B8A'];
const MODULE_COLOR_MAP=new Map(unique(window.MASTER_DATA.sessions.map(s=>s.module)).map((m,i)=>[m,MODULE_PALETTE[i%MODULE_PALETTE.length]]));
function moduleColor(module){if(!MODULE_COLOR_MAP.has(module))MODULE_COLOR_MAP.set(module,MODULE_PALETTE[MODULE_COLOR_MAP.size%MODULE_PALETTE.length]);return MODULE_COLOR_MAP.get(module)}
function queueServerSave(){if(!serverMode)return;clearTimeout(serverSaveTimer);serverSaveTimer=setTimeout(()=>fetch(apiUrl('api/state'),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataVersion:DATA_VERSION,sessions,records,updatedAt:new Date().toISOString()})}).catch(()=>toast('Server save failed')),250)}
const saveSchedule=()=>{localStorage.setItem(KEY,JSON.stringify(sessions));queueServerSave()};
const saveRecords=()=>{localStorage.setItem(RECORD_KEY,JSON.stringify(records));queueServerSave()};
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function optionize(el,values,selected){el.innerHTML=values.map(v=>`<option${v===selected?' selected':''}>${esc(v)}</option>`).join('')}

function viewFromLocation(){const view=location.pathname.split('/').filter(Boolean).pop();return VIEW_NAMES.includes(view)?view:(new URLSearchParams(location.search).get('view')||'timetable')}
function routeForView(name,shareToken){const url=new URL('index.html',APP_BASE);url.search='';url.searchParams.set('view',name);if(shareToken)url.searchParams.set('share',shareToken);return url}
function consumeStructuredLoginRedirect(){if(location.protocol==='file:'||location.pathname.split('/').filter(Boolean).pop()!=='login')return;const raw=new URLSearchParams(location.search).get('returnTo');if(!raw)return;try{const target=new URL(raw,location.origin);if(target.origin===location.origin&&target.pathname.startsWith(APP_BASE.pathname))history.replaceState({loginRedirect:true},'',target)}catch{}}
function switchView(name,{updateUrl=false,replace=false}={}){if(!VIEW_NAMES.includes(name))name='timetable';$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$(`#${name}View`).classList.add('active');$('#sidebar').classList.remove('open');if(updateUrl){const token=new URLSearchParams(location.search).get('share');history[replace?'replaceState':'pushState']({view:name},'',routeForView(name,token))}if(name==='hours')renderHours();if(name==='studentRepresentatives')renderStudentRepresentatives();if(name==='studentAbsences')renderStudentAbsences();if(name==='teachers')renderTeachers();if(name==='coordination'||name==='scientific')renderRecords(name);if(name==='competition')renderCompetition()}
function createShareLink(name){const token=globalThis.crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;const links=JSON.parse(localStorage.getItem('prep-cycle-share-links')||'{}');links[token]={view:name,createdAt:new Date().toISOString()};localStorage.setItem('prep-cycle-share-links',JSON.stringify(links));return routeForView(name,token).toString()}
async function copyShareLink(name){const link=createShareLink(name);try{await navigator.clipboard.writeText(link);toast('Share link copied')}catch{prompt('Copy this share link',link)}}
$$('.nav-item').forEach(n=>n.onclick=()=>switchView(n.dataset.view,{updateUrl:true}));$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');window.addEventListener('popstate',()=>switchView(viewFromLocation()));

function initFilters(){optionize($('#levelFilter'),[...LEVELS,ALL_LEVELS],LEVELS[0]);refreshSemesterFilter();optionize($('#moduleSearchList'),unique(sessions.map(s=>s.module)));optionize($('#teacherSearchList'),TEACHERS);optionize($('#roomSearchList'),window.MASTER_DATA.rooms);optionize($('#hoursDepartment'),[ALL_DEPARTMENTS,...unique(sessions.map(departmentOf))],ALL_DEPARTMENTS);optionize($('#hoursSemester'),[ALL_HOURS_SEMESTERS,...unique(sessions.map(s=>s.semester))],ALL_HOURS_SEMESTERS);$('#levelFilter').onchange=()=>{refreshSemesterFilter();refreshAudience();renderSchedule()};$('#semesterFilter').onchange=()=>{refreshAudience();renderSchedule()};$('#audienceFilter').onchange=renderSchedule;['moduleFilter','teacherFilter','roomFilter'].forEach(id=>$(`#${id}`).oninput=renderSchedule);['moduleFilter','teacherFilter'].forEach(id=>{$(`#${id}`).onfocus=activateResearchFilters;$(`#${id}`).onclick=activateResearchFilters});$('#exportExcel').onclick=()=>exportResearch('excel');$('#exportTeacherLoad').onclick=exportTeacherLoadExcel;$('#exportPdf').onclick=()=>exportResearch('pdf');$('#exportModuleZip').onclick=exportModulesZip;$$('.schedule-view-tab').forEach(b=>b.onclick=()=>{scheduleView=b.dataset.scheduleView;$$('.schedule-view-tab').forEach(x=>x.classList.toggle('active',x===b));renderSchedule()});}
function activateResearchFilters(){if($('#levelFilter').value===ALL_LEVELS&&$('#semesterFilter').value===ALL_SEMESTERS&&$('#audienceFilter').value==='all')return;$('#levelFilter').value=ALL_LEVELS;refreshSemesterFilter();refreshAudience();renderSchedule()}
function refreshSemesterFilter(){const level=$('#levelFilter').value||LEVELS[0];const values=level===ALL_LEVELS?[ALL_SEMESTERS,'Semester 1','Semester 2','Semester 3','Semester 4']:[ALL_SEMESTERS,...SEMESTERS[level]];optionize($('#semesterFilter'),values,level===ALL_LEVELS?ALL_SEMESTERS:values[1]||ALL_SEMESTERS)}
function baseFilterData(){const level=$('#levelFilter').value,semester=$('#semesterFilter').value;return sessions.filter(s=>(level===ALL_LEVELS||s.level===level)&&(semester===ALL_SEMESTERS||s.semester===semester))}
function refreshAudience(){const data=baseFilterData();let opts=[{v:'all',t:'All sections & groups'}];unique(data.map(s=>s.section)).forEach(sec=>opts.push({v:`section|${sec}`,t:sec}));unique(data.filter(s=>s.group).map(s=>`${s.section}|${s.group}`)).forEach(x=>{const [sec,g]=x.split('|');opts.push({v:`group|${sec}|${g}`,t:`${g} (${sec})`})});$('#audienceFilter').innerHTML=opts.map((o,i)=>`<option value="${esc(o.v)}"${i===0?' selected':''}>${esc(o.t)}</option>`).join('')}
function audienceMatch(s,val){if(val==='all')return true;const [kind,sec,group]=val.split('|');if(kind==='section')return s.section===sec;return s.section===sec&&(s.type==='Cours'||s.group===group)}
function prefixMatch(value,query){query=query.trim().toLocaleLowerCase();if(!query)return true;const valueLow=String(value||'').toLocaleLowerCase();return valueLow.includes(query)||valueLow.split(/\s+/).some(word=>word.startsWith(query))}
function selectedData(){const audience=$('#audienceFilter').value,module=$('#moduleFilter').value,teacher=$('#teacherFilter').value,room=$('#roomFilter').value;return baseFilterData().filter(s=>audienceMatch(s,audience)&&prefixMatch(s.module,module)&&prefixMatch(s.professor,teacher)&&prefixMatch(s.room,room))}
function countConflicts(data){let n=0;['room','professor'].forEach(k=>{const seen=new Set();data.forEach(s=>{const x=`${s.day}|${s.time}|${s[k]}`;if(seen.has(x))n++;seen.add(x)})});return n}
function renderSchedule(){const data=selectedData(),displayData=scheduleView==='courses'?data.filter(s=>s.type==='Cours'):data,semesterAll=baseFilterData();$('#scheduleMetrics').innerHTML=[['Visible sessions',displayData.length],['Professors',unique(displayData.map(s=>s.professor)).length],['Rooms in use',unique(displayData.map(s=>s.room)).length],['Conflicts',countConflicts(semesterAll)]].map(([a,b])=>`<div class="metric"><span>${a}</span><b>${b}</b></div>`).join('');const labels={days:'Days view',courses:'Courses only',sections:'Sections / Groups view',rooms:'Rooms view',available:'Available / Vacant rooms'};$('#activeViewLabel').textContent=labels[scheduleView];const grid=$('#scheduleGrid');grid.className=scheduleView==='days'||scheduleView==='courses'?'schedule-grid':'schedule-grid table-view';if(scheduleView==='days'||scheduleView==='courses')renderDaysView(grid,displayData);if(scheduleView==='sections')renderSectionsView(grid,data);if(scheduleView==='rooms')renderRoomsView(grid,data);if(scheduleView==='available')renderAvailableView(grid);$('#scheduleLegend').style.display=scheduleView==='available'?'none':'flex';$$('[data-id]').forEach(el=>el.onclick=()=>openSession(el.dataset.id))}
function renderDaysView(grid,data){let html='<div class="grid-cell header"></div>'+DAYS.map(d=>`<div class="grid-cell header">${d}</div>`).join('');TIMES.forEach(time=>{html+=`<div class="grid-cell time">${time.replace('-', '<br>')}</div>`;DAYS.forEach(day=>{const list=data.filter(s=>s.day===day&&s.time===time);html+=`<div class="grid-cell">${list.length?list.map(card).join(''):'<div class="empty-state">Available</div>'}</div>`})});grid.innerHTML=html}
function typeHtml(s){return`<span class="type-mark"><i class="dot ${s.type.toLowerCase()}"></i>${esc(s.type)}</span>`}
function renderSectionsView(grid,data){const sections=unique(data.map(s=>s.section));let html='<div class="section-matrix-wrap"><table class="sections-matrix"><thead><tr><th rowspan="2" class="sticky-section">SECTION</th><th rowspan="2" class="sticky-group">GROUPE</th>'+DAYS.map(d=>`<th colspan="5" class="day-band">${d}</th>`).join('')+'</tr><tr>'+DAYS.flatMap(()=>TIMES).map(t=>`<th class="time-band">${t}</th>`).join('')+'</tr></thead><tbody>';sections.forEach(section=>{let groups=unique(data.filter(s=>s.section===section&&s.group).map(s=>s.group));if(!groups.length)groups=['Lecture'];groups.forEach((group,gi)=>{html+='<tr>';if(gi===0)html+=`<th rowspan="${groups.length}" class="section-name sticky-section">${esc(section)}</th>`;html+=`<th class="group-name sticky-group">${esc(group)}</th>`;DAYS.forEach(day=>TIMES.forEach(time=>{const lecture=data.find(s=>s.section===section&&s.type==='Cours'&&s.day===day&&s.time===time);if(lecture){if(gi===0)html+=`<td rowspan="${groups.length}" class="matrix-slot lecture-matrix-cell" data-id="${lecture.id}" style="--module-color:${moduleColor(lecture.module)}"><div class="vertical-lecture"><b>${esc(lecture.module)}</b><span>${esc(lecture.professor)}</span><small>${esc(lecture.room)} · Cours</small></div></td>`}else{const ses=data.filter(s=>s.section===section&&s.group===group&&s.day===day&&s.time===time);html+=matrixSlot(ses)}}));html+='</tr>'});});html+='</tbody></table></div>';grid.innerHTML=sections.length?html:'<div class="empty-panel">No sessions match these filters.</div>'}
function matrixSlot(list){return`<td class="matrix-slot">${list.map(s=>`<button class="matrix-session" data-id="${s.id}" style="--module-color:${moduleColor(s.module)}"><b>${esc(s.module)}</b><span>${esc(s.type)} · ${esc(s.room)}</span><small>${esc(s.professor)}</small></button>`).join('')}</td>`}
function renderRoomsView(grid,data){const used=unique(data.map(s=>s.room));grid.innerHTML=used.length?used.map(room=>{const list=data.filter(s=>s.room===room).sort((a,b)=>DAYS.indexOf(a.day)-DAYS.indexOf(b.day)||TIMES.indexOf(a.time)-TIMES.indexOf(b.time));return`<section class="room-group"><h3>${esc(room)} <span class="status-tag">${list.length} sessions</span></h3><div class="room-session-list">${list.map(s=>`<button class="room-session" data-id="${s.id}"><b>${esc(s.module)}</b><span>${s.day} · ${s.time}</span><span>${esc(s.professor)} · ${esc(s.audience)}</span></button>`).join('')}</div></section>`}).join(''):'<div class="empty-panel">No occupied rooms match these filters.</div>'}
function renderAvailableView(grid){const report=freeRoomRows();grid.innerHTML=`<table class="schedule-data-table"><thead><tr>${report.headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${report.rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td><span class="availability-count">${r[2]}</span></td><td>${String(r[3]).split(', ').map(room=>`<span class="free-room-chip">${esc(room)}</span>`).join('')}</td></tr>`).join('')}</tbody></table>`}
function card(s){const color=moduleColor(s.module);return `<button class="session-card ${s.type.toLowerCase()}" data-id="${s.id}" style="--module-color:${color};border-left-color:${color};background:linear-gradient(135deg, ${color} 0%, rgba(255,255,255,0.98) 32%, rgba(255,255,255,0.98) 100%);"><strong style="color:${color}">${esc(s.module)}</strong><span>${esc(s.type)} · ${esc(s.room)}</span><span>${esc(s.professor)}</span><span>${esc(s.audience)}</span></button>`}

function setupEditor(){optionize($('#editLevel'),LEVELS);optionize($('#editDay'),DAYS);optionize($('#editTime'),TIMES);$('#editLevel').onchange=()=>{optionize($('#editSemester'),SEMESTERS[$('#editLevel').value]);updateRooms()};['editDay','editTime','editType','editModule','editSection','editGroup'].forEach(id=>$(`#${id}`).addEventListener(['editModule','editSection','editGroup'].includes(id)?'input':'change',updateRooms));$('#sessionForm').addEventListener('submit',saveSession);$('#deleteSession').onclick=deleteSession;$('#newSession').onclick=()=>openSession();$('#resetSchedule').onclick=()=>{if(confirm('Discard all timetable edits and restore the imported master timetable?')){sessions=structuredClone(window.MASTER_DATA.sessions);saveSchedule();refreshAudience();renderSchedule();toast('Imported timetable restored')}};}
function openSession(id){const s=sessions.find(x=>x.id===id);$('#sessionDialogTitle').textContent=s?'Edit session':'Add session';$('#sessionId').value=s?.id||'';$('#editDepartment').value=s?departmentOf(s):'Preparatory Cycle';$('#editLevel').value=s?.level||(LEVELS.includes($('#levelFilter').value)?$('#levelFilter').value:LEVELS[0]);optionize($('#editSemester'),SEMESTERS[$('#editLevel').value],s?.semester||(SEMESTERS[$('#editLevel').value].includes($('#semesterFilter').value)?$('#semesterFilter').value:SEMESTERS[$('#editLevel').value][0]));$('#editSection').value=s?.section||'';$('#editGroup').value=s?.group||'';$('#editDay').value=s?.day||DAYS[0];$('#editTime').value=s?.time||TIMES[0];$('#editModule').value=s?.module||'';$('#editType').value=s?.type||'TD';$('#editProfessor').value=s?.professor||'';$('#editRoom').dataset.current=s?.room||'';$('#deleteSession').style.visibility=s?'visible':'hidden';$('#formError').style.display='none';optionize($('#moduleList'),unique(sessions.map(x=>x.module)));optionize($('#professorList'),TEACHERS);updateRooms();if(s)$('#editRoom').value=s.room;$('#sessionDialog').showModal()}
function isEligible(room,type,module){const special=/^(AMPHI|SC)/.test(room),tp=room.startsWith('TP');if(special&&type!=='Cours')return false;if(tp&&!/(informatique|computer)/i.test(module))return false;return true}
function updateRooms(){const id=$('#sessionId').value,day=$('#editDay').value,time=$('#editTime').value,type=$('#editType').value,module=$('#editModule').value,current=$('#editRoom').dataset.current;const occupied=new Set(sessions.filter(s=>s.id!==id&&s.day===day&&s.time===time).map(s=>s.room));let rooms=window.MASTER_DATA.rooms.filter(r=>!occupied.has(r)&&isEligible(r,type,module));if(current&&!rooms.includes(current))rooms.unshift(current);$('#editRoom').innerHTML=rooms.map(r=>`<option value="${r}">${r}${r===current&&!isEligible(r,type,module)?' — imported exception':''}</option>`).join('');$('#vacancyNote').textContent=`${rooms.length} room${rooms.length===1?'':'s'} available for this slot and session type.`;updateAudienceAvailability()}
function hasAudienceConflict(day,time,id,section,group,type){return sessions.some(s=>s.id!==id&&s.day===day&&s.time===time&&s.section===section&&(type==='Cours'||s.type==='Cours'||s.group===group))}
function updateAudienceAvailability(){const id=$('#sessionId').value,section=$('#editSection').value.trim(),group=$('#editGroup').value.trim(),type=$('#editType').value,currentDay=$('#editDay').value,currentTime=$('#editTime').value,list=$('#audienceFreeSlots');if(!section){list.innerHTML='<div class="free-slot-empty">Enter a section to display its free times.</div>';$('#audienceRuleNote').textContent='';return}const free=[];DAYS.forEach(day=>TIMES.forEach(time=>{if(!hasAudienceConflict(day,time,id,section,group,type))free.push({day,time})}));list.innerHTML=free.length?free.map(x=>`<button type="button" class="free-slot-button ${x.day===currentDay&&x.time===currentTime?'selected':''}" data-free-day="${x.day}" data-free-time="${x.time}"><b>${x.day}</b><span>${x.time}</span></button>`).join(''):'<div class="free-slot-empty">No free time slots are available.</div>';list.querySelectorAll('.free-slot-button').forEach(b=>b.onclick=()=>{$('#editDay').value=b.dataset.freeDay;$('#editTime').value=b.dataset.freeTime;updateRooms()});$('#audienceRuleNote').textContent=type==='Cours'?`Only slots where ${section} and all of its constituent groups have no class are shown.`:`Only slots where ${section} has no lecture and ${group||'the selected group'} has no class are shown.`}
function saveSession(e){e.preventDefault();const id=$('#sessionId').value;const item={id:id||`S${Date.now()}`,department:$('#editDepartment').value.trim(),level:$('#editLevel').value,semester:$('#editSemester').value,section:$('#editSection').value.trim(),group:$('#editType').value==='Cours'?null:($('#editGroup').value.trim()||null),day:$('#editDay').value,time:$('#editTime').value,module:$('#editModule').value.trim(),type:$('#editType').value,professor:$('#editProfessor').value.trim(),room:$('#editRoom').value};item.audience=item.type==='Cours'?item.section:`${item.section} · ${item.group||'Unassigned group'}`;const err=validateSession(item,id);if(err){$('#formError').textContent=err;$('#formError').style.display='block';return}if(id)sessions[sessions.findIndex(s=>s.id===id)]=item;else sessions.push(item);if(!records.teachers.some(teacher=>teacher.toLowerCase()===item.professor.toLowerCase())){records.teachers.push(item.professor);saveRecords();refreshTeacherDirectory()}saveSchedule();optionize($('#hoursDepartment'),[ALL_DEPARTMENTS,...unique(sessions.map(departmentOf))],$('#hoursDepartment').value);$('#sessionDialog').close();refreshAudience();renderSchedule();toast(id?'Session updated':'Session added')}
function validateSession(item,id){if(item.type!=='Cours'&&!item.group)return'Choose a group for TD or TP sessions.';if(hasAudienceConflict(item.day,item.time,id,item.section,item.group,item.type))return item.type==='Cours'?`Lecture conflict: ${item.section} or one of its constituent groups already has a class at this time.`:`Class conflict: ${item.section} has a lecture or ${item.group} already has a class at this time.`;if(!item.room)return'No eligible vacant room is available. Change the slot or session details.';if(!isEligible(item.room,item.type,item.module))return'This room is not eligible: AMPHI/SC rooms are for lectures, and TP rooms are reserved for Computer Science.';const clash=sessions.find(s=>s.id!==id&&s.day===item.day&&s.time===item.time&&(s.room===item.room||s.professor.toLowerCase()===item.professor.toLowerCase()));if(!clash)return'';if(clash.room===item.room)return`Room conflict with ${clash.module} (${clash.audience}).`;return`Professor conflict with ${clash.module} (${clash.audience}).`}
function deleteSession(){const id=$('#sessionId').value;if(id&&confirm('Delete this session?')){sessions=sessions.filter(s=>s.id!==id);saveSchedule();$('#sessionDialog').close();refreshAudience();renderSchedule();toast('Session deleted')}}

function workload(data,includeDirectory=false){const map=new Map();if(includeDirectory)TEACHERS.forEach(professor=>map.set(professor,{professor,modules:new Set(),cours:new Map(),practical:0}));data.forEach(s=>{if(!map.has(s.professor))map.set(s.professor,{professor:s.professor,modules:new Set(),cours:new Map(),practical:0});const p=map.get(s.professor);p.modules.add(s.module);if(s.type==='Cours')p.cours.set(s.module,(p.cours.get(s.module)||0)+1);else p.practical++});return [...map.values()].map(p=>{let hours=p.practical*1.5;let lectures=0;p.cours.forEach(n=>{lectures+=n;hours+=n*2.25});return{...p,hours,lectures}}).sort((a,b)=>b.hours-a.hours||a.professor.localeCompare(b.professor))}
function hoursScope(){const department=$('#hoursDepartment').value,semester=$('#hoursSemester').value,type=$('#hoursType').value;const filtered=sessions.filter(s=>(department===ALL_DEPARTMENTS||departmentOf(s)===department)&&(semester===ALL_HOURS_SEMESTERS||s.semester===semester)&&(type==='all'||s.type===type));return{filtered,isFiltered:department!==ALL_DEPARTMENTS||semester!==ALL_HOURS_SEMESTERS||type!=='all'}}
function hoursRows(){const {filtered,isFiltered}=hoursScope(),q=$('#hoursSearch').value;return workload(filtered,!isFiltered).filter(p=>prefixMatch(p.professor,q))}
function renderHours(){const rows=hoursRows();$('#hoursBody').innerHTML=rows.map(p=>`<tr class="${p.hours<9?'low-load':''}"><td><b>${esc(p.professor)}</b></td><td>${esc([...p.modules].join(', ')||'—')}</td><td>${p.lectures}</td><td>${p.practical}</td><td class="numeric">${formatHours(p.hours)}</td><td><span class="status-tag">${p.hours<9?'Below 9h':'Compliant'}</span></td></tr>`).join('')||'<tr><td colspan="6" class="empty-panel">No professors found.</td></tr>'}
function formatHours(h){const hr=Math.floor(h),m=Math.round((h-hr)*60);return`${hr}h ${String(m).padStart(2,'0')}`}
function csvCell(value){return`"${String(value??'').replace(/"/g,'""')}"`}
function exportHoursExcel(){exportTableExcel('Professors Teaching Hours',teacherRows(),'teaching-hours.xls')}
function teacherExportName(name){const normalized=String(name).trim().toLocaleLowerCase();const exact=TEACHERS.find(teacher=>teacher.toLocaleLowerCase()===normalized);if(exact)return exact;const surname=normalized.split(/\s+/)[0],matches=TEACHERS.filter(teacher=>teacher.toLocaleLowerCase().split(/\s+/)[0]===surname);return matches.length===1?matches[0]:name}
function teacherLoadRows(){const grouped=new Map();sessions.forEach(s=>{const teacher=teacherExportName(s.professor),group=s.group||s.section,key=[teacher,s.level,s.semester,s.module,s.type,s.section,group].join('|');const row=grouped.get(key)||{teacher,level:s.level,semester:s.semester,module:s.module,type:s.type,section:s.section,groups:group,sessions:0,hours:0};row.sessions++;row.hours+=s.type==='Cours'?2.25:1.5;grouped.set(key,row)});TEACHERS.forEach(teacher=>{if(![...grouped.values()].some(row=>row.teacher===teacher))grouped.set(`${teacher}|unassigned`,{teacher,level:'—',semester:'—',module:'No assigned module',type:'—',section:'—',groups:'—',sessions:0,hours:0})});return{headers:['Teacher','Academic level','Semester','Module','Session type','Section','Group(s)','Sessions','Total hours'],rows:[...grouped.values()].sort((a,b)=>a.teacher.localeCompare(b.teacher)||a.level.localeCompare(b.level)||a.module.localeCompare(b.module)||a.groups.localeCompare(b.groups)).map(row=>[row.teacher,row.level,row.semester,row.module,row.type,row.section,row.groups,row.sessions,formatHours(row.hours)])}}
function exportTeacherLoadExcel(){exportTableExcel('Teachers Pedagogical Load',teacherLoadRows(),'teachers-pedagogical-load.xls')}
['hoursDepartment','hoursSemester','hoursType'].forEach(id=>$(`#${id}`).onchange=renderHours);$('#hoursSearch').oninput=renderHours;$('#exportHours').onclick=exportHoursExcel;$('#shareHours').onclick=()=>copyShareLink('hours');

function freeRoomRows(){const rows=[];DAYS.forEach(day=>TIMES.forEach(time=>{const occupied=new Set(sessions.filter(s=>s.day===day&&s.time===time).map(s=>s.room));const free=window.MASTER_DATA.rooms.filter(r=>!occupied.has(r));rows.push([day,time,free.length,free.join(', ')])}));return{headers:['Day','Time slot','Number of free rooms','Free rooms'],rows}}
function rowsForSessions(data,order='days'){const sorted=data.slice().sort((a,b)=>order==='sections'?(a.section.localeCompare(b.section)||(a.group||'').localeCompare(b.group||'')||DAYS.indexOf(a.day)-DAYS.indexOf(b.day)||TIMES.indexOf(a.time)-TIMES.indexOf(b.time)):order==='rooms'?(a.room.localeCompare(b.room)||DAYS.indexOf(a.day)-DAYS.indexOf(b.day)||TIMES.indexOf(a.time)-TIMES.indexOf(b.time)):(DAYS.indexOf(a.day)-DAYS.indexOf(b.day)||TIMES.indexOf(a.time)-TIMES.indexOf(b.time)));return{headers:order==='rooms'?['Room','Day','Time slot','Module','Professor','Type','Section / group']:order==='sections'?['Section / group','Day','Time slot','Module','Professor','Type','Room']:['Day','Time slot','Module','Professor','Type','Section / group','Room'],rows:sorted.map(s=>order==='rooms'?[s.room,s.day,s.time,s.module,s.professor,s.type,s.audience]:order==='sections'?[s.audience,s.day,s.time,s.module,s.professor,s.type,s.room]:[s.day,s.time,s.module,s.professor,s.type,s.audience,s.room])}}
function sessionRows(){return rowsForSessions(selectedData(),'days')}
function teacherRows(){return{headers:['Professor','Modules','Lectures','TD / TP','Total load','Status'],rows:hoursRows().map(p=>[p.professor,[...p.modules].join(', ')||'—',p.lectures,p.practical,formatHours(p.hours),p.hours<9?'Below 9h':'Compliant'])}}
function currentReport(){const lectureData=selectedData().filter(s=>s.type==='Cours');if(scheduleView==='available')return{title:'Available and vacant rooms',...freeRoomRows()};if(scheduleView==='sections')return{title:'Timetable by sections and groups',...rowsForSessions(selectedData(),'sections')};if(scheduleView==='rooms')return{title:'Timetable by rooms',...rowsForSessions(selectedData(),'rooms')};if(scheduleView==='courses')return{title:'Timetable by days (courses only)',...rowsForSessions(lectureData,'days')};return{title:'Timetable by days',...sessionRows()}}
function reportFilename(title,ext){const stamp=new Date().toISOString().slice(0,10),base=title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return`${base}-${stamp}.${ext}`}
function exportLayoutData(){const module=$('#moduleFilter').value,teacher=$('#teacherFilter').value,room=$('#roomFilter').value;const data=baseFilterData().filter(s=>prefixMatch(s.module,module)&&prefixMatch(s.professor,teacher)&&prefixMatch(s.room,room));return scheduleView==='courses'?data.filter(s=>s.type==='Cours'):data}
function exportResearch(format){const report=currentReport();if(format==='excel'){const data=exportLayoutData(),blob=scheduleView==='rooms'?buildRoomsMatrixExcel(data):scheduleView==='available'?buildExcelBlob(report.title,report):buildMasterMatrixExcel(data);downloadBlob(blob,reportFilename(report.title,'xls'));toast('Excel timetable exported')}else exportTablePdf(report.title,report.headers,report.rows,reportFilename(report.title,'pdf'))}
function xmlEsc(v){return String(v??'').replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]))}
function buildExcelBlob(title,table){const cols=table.headers.map((_,i)=>Math.min(320,Math.max(90,...table.rows.slice(0,100).map(r=>String(r[i]??'').length*7))));const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Title"><Font ss:Bold="1" ss:Size="16" ss:Color="#FFFFFF"/><Interior ss:Color="#123F36" ss:Pattern="Solid"/><Alignment ss:Horizontal="Center"/></Style><Style ss:ID="Head"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#1E6758" ss:Pattern="Solid"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/></Borders></Style><Style ss:ID="Cell"><Alignment ss:Vertical="Top" ss:WrapText="1"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#D9E2DE"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#D9E2DE"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#D9E2DE"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#D9E2DE"/></Borders></Style></Styles><Worksheet ss:Name="Report"><Table>${cols.map(w=>`<Column ss:Width="${w}"/>`).join('')}<Row ss:Height="28"><Cell ss:MergeAcross="${table.headers.length-1}" ss:StyleID="Title"><Data ss:Type="String">${xmlEsc(title)}</Data></Cell></Row><Row>${table.headers.map(h=>`<Cell ss:StyleID="Head"><Data ss:Type="String">${xmlEsc(h)}</Data></Cell>`).join('')}</Row>${table.rows.map(r=>`<Row>${r.map(v=>`<Cell ss:StyleID="Cell"><Data ss:Type="String">${xmlEsc(v)}</Data></Cell>`).join('')}</Row>`).join('')}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>2</SplitHorizontal><TopRowBottomPane>2</TopRowBottomPane><Selected/></WorksheetOptions></Worksheet></Workbook>`;return new Blob([xml],{type:'application/vnd.ms-excel'})}
function moduleStyleMap(data){return new Map(unique(data.map(s=>s.module)).map((m,i)=>[m,i]))}
function sessionText(s,includeAudience=true){return`${s.module} (${s.type})\n${s.professor}${includeAudience&&s.group?`\nGroupe : ${s.group}`:''}\nSalle : ${s.room}`}
function excelBorders(){return'<Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#B8C4CC"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#B8C4CC"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#B8C4CC"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#B8C4CC"/>'}
function matrixExcelStyles(data){const mods=moduleStyleMap(data);let styles=`<Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Center" ss:WrapText="1"/><Font ss:FontName="Arial" ss:Size="10"/></Style><Style ss:ID="Hdr"><Font ss:Bold="1"/><Interior ss:Color="#FFFF00" ss:Pattern="Solid"/><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders>${excelBorders()}</Borders></Style><Style ss:ID="Label"><Font ss:Bold="1"/><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders>${excelBorders()}</Borders></Style><Style ss:ID="Section"><Font ss:Bold="1"/><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:Rotate="90"/><Borders>${excelBorders()}</Borders></Style><Style ss:ID="Blank"><Borders>${excelBorders()}</Borders></Style>`;mods.forEach((i,m)=>{const color=moduleColor(m);styles+=`<Style ss:ID="M${i}"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="${color}" ss:Pattern="Solid"/><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/><Borders>${excelBorders()}</Borders></Style><Style ss:ID="C${i}"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="${color}" ss:Pattern="Solid"/><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1" ss:Rotate="90"/><Borders>${excelBorders()}</Borders></Style>`});return{mods,styles}}
function xcell(value,style='Blank',attrs='',index=null){return`<Cell${index?` ss:Index="${index}"`:''} ss:StyleID="${style}"${attrs}><Data ss:Type="String">${xmlEsc(value)}</Data></Cell>`}
function buildMasterMatrixExcel(data){const {mods,styles}=matrixExcelStyles(data),sections=unique(data.map(s=>s.section));let rows=`<Row ss:Height="400">${xcell('','Blank')}${xcell('','Blank')}${DAYS.map(d=>xcell(d.toUpperCase(),'Hdr',' ss:MergeAcross="4"')).join('')}</Row><Row ss:Height="400">${xcell('Section','Label')}${xcell('Groupe','Label')}${DAYS.flatMap(()=>TIMES).map(t=>xcell(` ${t}`,'Hdr')).join('')}</Row>`;sections.forEach(section=>{let groups=unique(data.filter(s=>s.section===section&&s.group).map(s=>s.group));if(!groups.length)groups=['Lecture'];groups.forEach((group,gi)=>{let cells='';if(gi===0)cells+=xcell(section,'Section',groups.length>1?` ss:MergeDown="${groups.length-1}"`:'',1);cells+=xcell(group,'Label','',2);let col=3;DAYS.forEach(day=>TIMES.forEach(time=>{const lecture=data.find(s=>s.section===section&&s.type==='Cours'&&s.day===day&&s.time===time);if(lecture){if(gi===0)cells+=xcell(sessionText(lecture,false),`C${mods.get(lecture.module)}`,groups.length>1?` ss:MergeDown="${groups.length-1}"`:'',col)}else{const ses=data.find(s=>s.section===section&&s.group===group&&s.day===day&&s.time===time);cells+=ses?xcell(sessionText(ses),`M${mods.get(ses.module)}`,'',col):xcell('','Blank','',col)}col++}));rows+=`<Row ss:Height="409">${cells}</Row>`})});const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles>${styles}</Styles><Worksheet ss:Name="Vue matrice"><Table ss:ExpandedColumnCount="32"><Column ss:Width="70"/><Column ss:Width="70"/>${Array(30).fill('<Column ss:Width="120"/>').join('')}${rows}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>2</SplitHorizontal><TopRowBottomPane>2</TopRowBottomPane><SplitVertical>2</SplitVertical><LeftColumnRightPane>2</LeftColumnRightPane></WorksheetOptions></Worksheet></Workbook>`;return new Blob([xml],{type:'application/vnd.ms-excel'})}
function buildRoomsMatrixExcel(data){const {mods,styles}=matrixExcelStyles(data),rooms=window.MASTER_DATA.rooms;let rows=`<Row ss:Height="64">${xcell('Jour','Label')}${xcell('Horaire','Label')}${rooms.map(r=>xcell(r,'Hdr')).join('')}</Row>`;DAYS.forEach(day=>TIMES.forEach((time,ti)=>{let cells='';if(ti===0)cells+=xcell(day,'Section',' ss:MergeDown="4"',1);cells+=xcell(time,'Label','',2);rooms.forEach((room,i)=>{const ses=data.find(s=>s.day===day&&s.time===time&&s.room===room);cells+=ses?xcell(`${ses.module} (${ses.type})\n${ses.audience}\n${ses.professor}\nSalle : ${ses.room}`,`M${mods.get(ses.module)}`,'',i+3):xcell('','Blank','',i+3)});rows+=`<Row ss:Height="130">${cells}</Row>`}));const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles>${styles}</Styles><Worksheet ss:Name="Vue salles"><Table><Column ss:Width="85"/><Column ss:Width="105"/>${rooms.map(()=>'<Column ss:Width="180"/>').join('')}${rows}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>1</SplitHorizontal><TopRowBottomPane>1</TopRowBottomPane><SplitVertical>2</SplitVertical><LeftColumnRightPane>2</LeftColumnRightPane></WorksheetOptions></Worksheet></Workbook>`;return new Blob([xml],{type:'application/vnd.ms-excel'})}
function buildModuleExcelBlob(module,data,color){const cells=TIMES.map(time=>`<Row ss:Height="130">${xcell(time,'Time')}${DAYS.map(day=>{const list=data.filter(s=>s.day===day&&s.time===time);return xcell(list.map(s=>`${s.module} — ${s.type}\n${s.professor}\n${s.room}${s.group?` · ${s.group}`:''}`).join('\n────────\n'),list.length?'Module':'Blank')}).join('')}</Row>`).join('');const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Title"><Font ss:Bold="1" ss:Size="18"/><Alignment ss:Horizontal="Left" ss:Vertical="Center"/></Style><Style ss:ID="Header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#265B86" ss:Pattern="Solid"/><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders>${excelBorders()}</Borders></Style><Style ss:ID="Time"><Font ss:Bold="1"/><Alignment ss:Horizontal="Center" ss:Vertical="Center"/><Borders>${excelBorders()}</Borders></Style><Style ss:ID="Module"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="${color}" ss:Pattern="Solid"/><Alignment ss:Vertical="Top" ss:WrapText="1"/><Borders>${excelBorders()}</Borders></Style><Style ss:ID="Blank"><Borders>${excelBorders()}</Borders></Style></Styles><Worksheet ss:Name="${xmlEsc(safeName(module).slice(0,31))}"><Table><Column ss:Width="90"/>${DAYS.map(()=>'<Column ss:Width="190"/>').join('')}<Row ss:Height="32"><Cell ss:StyleID="Title" ss:MergeAcross="6"><Data ss:Type="String">Pedagogical timetable — Module</Data></Cell></Row><Row ss:Height="24"><Cell ss:StyleID="Title" ss:MergeAcross="6"><Data ss:Type="String">${xmlEsc(module)} — ${data.length} session(s)</Data></Cell></Row><Row ss:Height="30">${xcell('Time slot','Header')}${DAYS.map(d=>xcell(d,'Header')).join('')}</Row>${cells}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>3</SplitHorizontal><TopRowBottomPane>3</TopRowBottomPane><FitToPage/></WorksheetOptions></Worksheet></Workbook>`;return new Blob([xml],{type:'application/vnd.ms-excel'})}
function hexRgb(hex){return[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255)}
function onePagePdf(content,W,H){const objs=[];objs[1]='<< /Type /Catalog /Pages 2 0 R >>';objs[2]='<< /Type /Pages /Kids [5 0 R] /Count 1 >>';objs[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';objs[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';objs[5]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents 6 0 R >>`;objs[6]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`;let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objs.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
function pdfTextWidth(text,fontSize){return String(text).length*fontSize*.54}
function pdfCenteredX(text,fontSize,x,width){return Math.max(x+4,x+(width-pdfTextWidth(text,fontSize))/2)}
function pdfFitSize(text,maxSize,minSize,width){return Math.max(minSize,Math.min(maxSize,width/(Math.max(1,String(text).length)*.54)))}
function buildModulePdfBlob(module,data,color){const W=1191,H=842,left=40,bottom=55,top=720,timeW=82,dayW=(W-left*2-timeW)/6,rowH=(top-bottom)/5,[r,g,b]=hexRgb(color),title='Pedagogical timetable - Module',subtitle=`${module} - ${data.length} session(s)`,subtitleSize=pdfFitSize(subtitle,18,12,W-left*2);let c=`BT /F2 24 Tf 0.08 0.12 0.16 rg ${pdfCenteredX(title,24,left,W-left*2)} 792 Td (${pdfSafe(title)}) Tj ET BT /F2 ${subtitleSize.toFixed(1)} Tf ${pdfCenteredX(subtitle,subtitleSize,left,W-left*2)} 762 Td (${pdfSafe(subtitle)}) Tj ET\n`;c+=`0.149 0.357 0.525 rg ${left} ${top} ${W-left*2} 34 re f\n`;const timeHeading='TIME SLOT';c+=`BT /F2 10 Tf 1 1 1 rg ${pdfCenteredX(timeHeading,10,left,timeW)} ${top+11} Td (${timeHeading}) Tj ET\n`;DAYS.forEach((d,i)=>{const label=d.toUpperCase(),x=left+timeW+i*dayW;c+=`BT /F2 12 Tf 1 1 1 rg ${pdfCenteredX(label,12,x,dayW)} ${top+10} Td (${label}) Tj ET\n`});TIMES.forEach((time,ri)=>{const y=top-(ri+1)*rowH;c+=`0.72 G ${left} ${y} ${W-left*2} ${rowH} re S\nBT /F2 11 Tf 0.08 0.12 0.16 rg ${pdfCenteredX(time,11,left,timeW)} ${y+rowH/2-4} Td (${time}) Tj ET\n`;DAYS.forEach((day,di)=>{const x=left+timeW+di*dayW,list=data.filter(s=>s.day===day&&s.time===time);c+=`0.82 G ${x} ${y} m ${x} ${y+rowH} l S\n`;if(list.length){const gap=4,ch=Math.min(54,(rowH-gap*(list.length+1))/Math.min(list.length,3)),crowded=list.length>=3;list.slice(0,3).forEach((s,i)=>{const cy=y+rowH-gap-(i+1)*ch-i*gap,lineGap=crowded?9.5:14,topInset=crowded?10:15,maxSizes=crowded?[8,7,6.5]:[11,9,9],minSizes=crowded?[6.5,6,6]:[8.5,7.5,7.5];c+=`${r.toFixed(3)} ${g.toFixed(3)} ${b.toFixed(3)} rg ${x+4} ${cy} ${dayW-8} ${ch} re f\n`;[s.module,s.professor,`${s.room}${s.group?` - ${s.group}`:''} - ${s.type}`].forEach((line,j)=>{const safe=pdfSafe(line).slice(0,34),fontSize=pdfFitSize(safe,maxSizes[j],minSizes[j],dayW-16),lineY=cy+ch-topInset-j*lineGap;if(lineY>cy+3)c+=`BT /F2 ${fontSize.toFixed(1)} Tf 1 1 1 rg ${pdfCenteredX(safe,fontSize,x+4,dayW-8)} ${lineY.toFixed(1)} Td (${safe}) Tj ET\n`})})}})});return onePagePdf(c,W,H)}

function exportTableExcel(title,table,filename){downloadBlob(buildExcelBlob(title,table),filename);toast('Excel report exported')}
function pdfSafe(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,' ').replace(/([\\()])/g,'\\$1')}
function buildPdfBlob(title,headers,rows){const W=842,H=595,left=30,top=535,rowH=17,perPage=26;const widths=headers.length===4?[100,105,95,482]:headers.length===6?[150,250,65,65,80,100]:headers.length===7?[80,70,70,130,120,55,257]:Array(headers.length).fill(782/headers.length);const pages=[];for(let p=0;p<Math.max(1,Math.ceil(rows.length/perPage));p++){const part=rows.slice(p*perPage,(p+1)*perPage);let c=`0.071 0.247 0.212 rg ${left} 554 782 25 re f BT /F1 14 Tf 1 1 1 rg ${left+8} 563 Td (${pdfSafe(title)}) Tj ET\n`;let y=top;c+=`0.118 0.404 0.345 rg ${left} ${y} 782 ${rowH} re f\n`;let x=left;headers.forEach((h,i)=>{c+=`BT /F1 7 Tf 1 1 1 rg ${x+3} ${y+5} Td (${pdfSafe(h).slice(0,40)}) Tj ET\n`;x+=widths[i]});y-=rowH;part.forEach(r=>{x=left;c+=`0.86 G ${left} ${y} 782 ${rowH} re S\n`;r.forEach((v,i)=>{const cap=Math.max(6,Math.floor(widths[i]/4.5));c+=`BT /F1 6.5 Tf 0.1 0.13 0.12 rg ${x+3} ${y+5} Td (${pdfSafe(v).slice(0,cap)}) Tj ET\n`;x+=widths[i];if(i<r.length-1)c+=`0.86 G ${x} ${y} m ${x} ${y+rowH} l S\n`});y-=rowH});c+=`BT /F1 7 Tf 0.35 0.4 0.38 rg 760 18 Td (Page ${p+1}) Tj ET`;pages.push(c)}const objs=[];objs[1]='<< /Type /Catalog /Pages 2 0 R >>';const kids=pages.map((_,i)=>`${4+i*2} 0 R`).join(' ');objs[2]=`<< /Type /Pages /Kids [${kids}] /Count ${pages.length} >>`;objs[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';pages.forEach((c,i)=>{const pn=4+i*2,cn=pn+1;objs[pn]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${cn} 0 R >>`;objs[cn]=`<< /Length ${c.length} >>\nstream\n${c}\nendstream`});let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objs.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
function exportTablePdf(title,headers,rows,filename){downloadBlob(buildPdfBlob(title,headers,rows),filename);toast('PDF report exported')}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function u16(v){return new Uint8Array([v&255,(v>>>8)&255])}function u32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255])}function joinBytes(parts){const n=parts.reduce((a,b)=>a+b.length,0),out=new Uint8Array(n);let o=0;parts.forEach(b=>{out.set(b,o);o+=b.length});return out}
async function buildZip(entries){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const entry of entries){const name=enc.encode(entry.name),data=new Uint8Array(await entry.blob.arrayBuffer()),crc=crc32(data),size=data.length;const local=joinBytes([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(size),u32(size),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(joinBytes([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(size),u32(size),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const central=joinBytes(centrals),end=joinBytes([u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(central.length),u32(offset),u16(0)]);return new Blob([...locals,central,end],{type:'application/zip'})}
function safeName(v){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').replace(/^_|_$/g,'')}
async function exportModulesZip(){const moduleQuery=$('#moduleFilter').value,data=baseFilterData().filter(s=>prefixMatch(s.module,moduleQuery)),modules=unique(data.map(s=>s.module));if(!modules.length){toast('No module sessions to export');return}$('#exportModuleZip').disabled=true;$('#exportModuleZip').textContent='Building ZIP…';try{const entries=[];for(const module of modules){const moduleData=data.filter(s=>s.module===module),base=safeName(module),color=moduleColor(module);entries.push({name:`${base}/${base}_Day_View.xls`,blob:buildModuleExcelBlob(module,moduleData,color)},{name:`${base}/${base}_Day_View.pdf`,blob:buildModulePdfBlob(module,moduleData,color)})}const zip=await buildZip(entries);downloadBlob(zip,`individual-module-timetables-${new Date().toISOString().slice(0,10)}.zip`);toast(`${modules.length} individual module timetable${modules.length===1?'':'s'} exported`)}finally{$('#exportModuleZip').disabled=false;$('#exportModuleZip').innerHTML='<span>ZIP</span> Modules ZIP'}}

const DB='prep-cycle-files';function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putFile(key,file){if(!file)return null;if(serverMode){const r=await fetch(apiUrl(`api/files/${encodeURIComponent(key)}`),{method:'PUT',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});if(!r.ok)throw new Error('File save failed');return{name:file.name,key,type:file.type}}const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put(file,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});return{name:file.name,key,type:file.type}}
async function getFile(key){if(serverMode){const r=await fetch(apiUrl(`api/files/${encodeURIComponent(key)}`));if(!r.ok)return null;return r.blob()}const d=await db();return new Promise((res,rej)=>{const r=d.transaction('files').objectStore('files').get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-file]');if(a){e.preventDefault();const f=await getFile(a.dataset.file);if(f)downloadBlob(f,a.dataset.name)}});

function normalizeExtendedRecords(){const aliases=new Map([['BERKIK','MERKIK']]);sessions.forEach(session=>{if(aliases.has(session.professor))session.professor=aliases.get(session.professor)});for(const kind of ['coordination','scientific','competition','studentRepresentatives','studentAbsences'])if(!Array.isArray(records[kind]))records[kind]=[];const storedTeachers=Array.isArray(records.teachers)?records.teachers:[];records.teachers=unique([...storedTeachers,...(window.ALL_TEACHERS||[]),...sessions.map(s=>s.professor)].map(teacher=>aliases.get(teacher)||teacher));TEACHERS=unique(records.teachers)}
function levelSemesterFields(prefix,selectedLevel=LEVELS[0],selectedSemester){const levelOptions=LEVELS.map(level=>`<option${level===selectedLevel?' selected':''}>${esc(level)}</option>`).join(''),semesterOptions=SEMESTERS[selectedLevel].map(semester=>`<option${semester===selectedSemester?' selected':''}>${esc(semester)}</option>`).join('');return`<div class="field"><label>Level</label><select name="${prefix}Level" required>${levelOptions}</select></div><div class="field"><label>Semester</label><select name="${prefix}Semester" required>${semesterOptions}</select></div>`}
function connectLevelSemester(form,prefix){const level=form.elements[`${prefix}Level`],semester=form.elements[`${prefix}Semester`];if(!level||!semester)return;const refresh=()=>optionize(semester,SEMESTERS[level.value],semester.value);level.onchange=refresh;refresh()}
function removeStudentRecord(kind,id){if(!confirm('Delete this student record?'))return;records[kind]=records[kind].filter(item=>item.id!==id);saveRecords();kind==='studentRepresentatives'?renderStudentRepresentatives():renderStudentAbsences();toast('Student record deleted')}
function representativeExportRows(){return{headers:['Role','Student ID','First & Last Name','Level','Group','Phone Number','Email'],rows:records.studentRepresentatives.slice().sort((a,b)=>a.level.localeCompare(b.level)||a.group.localeCompare(b.group)||a.role.localeCompare(b.role)||a.fullName.localeCompare(b.fullName)).map(r=>[r.role,r.studentId,r.fullName,r.level,r.group,r.phone,r.email])}}
function absenceExportRows(){return{headers:['Absence Date','Student ID','First & Last Name','Level','Semester','Reason'],rows:records.studentAbsences.slice().sort((a,b)=>String(b.absenceDate).localeCompare(String(a.absenceDate))||a.level.localeCompare(b.level)||a.fullName.localeCompare(b.fullName)).map(r=>[r.absenceDate,r.studentId,r.fullName,r.level,r.semester,r.reason==='Other Reason'&&r.otherReason?`${r.reason}: ${r.otherReason}`:r.reason])}}
function teacherExportRows(){return{headers:['Teacher','Timetable Sessions','Modules'],rows:TEACHERS.map(name=>{const assigned=sessions.filter(s=>s.professor===name);return[name,assigned.length,unique(assigned.map(s=>s.module)).join(', ')||'—']})}}
function exportOrganizedList(title,table,base,format){if(format==='excel')exportTableExcel(title,table,`${base}.xls`);else exportTablePdf(title,table.headers,table.rows,`${base}.pdf`)}

function renderStudentRepresentatives(){const view=$('#studentRepresentativesView');view.innerHTML=`<div class="page-heading"><div><span class="eyebrow">Student management</span><h2>Student Representatives</h2><p>Register class, group, and level representatives.</p></div><div class="heading-actions"><button class="button export-excel" id="exportRepresentativesExcel"><span>▦</span> Excel</button><button class="button export-pdf" id="exportRepresentativesPdf"><span>PDF</span> PDF</button></div></div><div class="management-grid"><form id="representativeForm" class="panel form-panel stack"><h3>Add representative</h3><div class="field"><label>Representative role</label><select name="role" required><option>Class Representative</option><option>Group Representative</option><option>Level Representative</option></select></div><div class="form-row"><div class="field"><label>Student ID</label><input name="studentId" required /></div><div class="field"><label>First &amp; Last Name</label><input name="fullName" required /></div></div><div class="field"><label>Level</label><select name="level" required>${LEVELS.map(level=>`<option>${esc(level)}</option>`).join('')}</select></div><div class="field"><label>Group</label><input name="group" required placeholder="Group 01" /></div><div class="form-row"><div class="field"><label>Phone Number</label><input name="phone" type="tel" required /></div><div class="field"><label>Email</label><input name="email" type="email" required /></div></div><button class="button primary" type="submit">Save representative</button></form><div class="panel data-list"><h3>Registered representatives <span class="record-count">(${records.studentRepresentatives.length})</span></h3><div id="representativeList"></div></div></div>`;const form=$('#representativeForm');$('#exportRepresentativesExcel').onclick=()=>exportOrganizedList('Student Representatives',representativeExportRows(),'student-representatives','excel');$('#exportRepresentativesPdf').onclick=()=>exportOrganizedList('Student Representatives',representativeExportRows(),'student-representatives','pdf');form.onsubmit=saveStudentRepresentative;const list=$('#representativeList');list.innerHTML=records.studentRepresentatives.length?records.studentRepresentatives.slice().reverse().map(r=>`<article class="data-card"><div><h4>${esc(r.fullName)}</h4><div class="record-meta"><span>${esc(r.role)}</span><span>${esc(r.level)}</span><span>${esc(r.group)}</span></div><p><b>Student ID:</b> ${esc(r.studentId)}</p><p>${esc(r.phone)} · ${esc(r.email)}</p></div><div class="data-card-actions"><button class="button danger" data-delete-representative="${esc(r.id)}">Delete</button></div></article>`).join(''):'<div class="empty-panel">No student representatives registered yet.</div>';list.querySelectorAll('[data-delete-representative]').forEach(button=>button.onclick=()=>removeStudentRecord('studentRepresentatives',button.dataset.deleteRepresentative))}
function saveStudentRepresentative(e){e.preventDefault();const f=new FormData(e.target),studentId=String(f.get('studentId')).trim();if(records.studentRepresentatives.some(r=>r.studentId.toLowerCase()===studentId.toLowerCase()&&r.role===f.get('role'))){toast('This student already has that representative role');return}records.studentRepresentatives.push({id:String(Date.now()),role:f.get('role'),studentId,fullName:String(f.get('fullName')).trim(),level:f.get('level'),group:String(f.get('group')).trim(),phone:String(f.get('phone')).trim(),email:String(f.get('email')).trim()});saveRecords();renderStudentRepresentatives();toast('Student representative saved')}

function renderStudentAbsences(){const view=$('#studentAbsencesView');view.innerHTML=`<div class="page-heading"><div><span class="eyebrow">Student management</span><h2>Student Absences</h2><p>Record dated absences and their supporting reason.</p></div><div class="heading-actions"><button class="button export-excel" id="exportAbsencesExcel"><span>▦</span> Excel</button><button class="button export-pdf" id="exportAbsencesPdf"><span>PDF</span> PDF</button></div></div><div class="management-grid"><form id="absenceForm" class="panel form-panel stack"><h3>Add absence</h3>${levelSemesterFields('absence')}<div class="form-row"><div class="field"><label>Student ID</label><input name="studentId" required /></div><div class="field"><label>First &amp; Last Name</label><input name="fullName" required /></div></div><div class="field"><label>Absence Date</label><input name="absenceDate" type="date" required /></div><div class="field"><label>Reason for Absence</label><select name="reason" required><option>Illness</option><option>Death/Bereavement</option><option>Official Summons</option><option>Other Reason</option></select></div><div class="field reason-other"><label>Other Reason Details</label><input name="otherReason" /></div><button class="button primary" type="submit">Save absence</button></form><div class="panel data-list"><h3>Absence records <span class="record-count">(${records.studentAbsences.length})</span></h3><div id="absenceList"></div></div></div>`;const form=$('#absenceForm');$('#exportAbsencesExcel').onclick=()=>exportOrganizedList('Student Absences',absenceExportRows(),'student-absences','excel');$('#exportAbsencesPdf').onclick=()=>exportOrganizedList('Student Absences',absenceExportRows(),'student-absences','pdf');connectLevelSemester(form,'absence');const reason=form.elements.reason,other=form.elements.otherReason,otherField=other.closest('.reason-other');const refreshOther=()=>{const active=reason.value==='Other Reason';otherField.classList.toggle('visible',active);other.required=active;if(!active)other.value=''};reason.onchange=refreshOther;refreshOther();form.onsubmit=saveStudentAbsence;const list=$('#absenceList');list.innerHTML=records.studentAbsences.length?records.studentAbsences.slice().sort((a,b)=>String(b.absenceDate).localeCompare(String(a.absenceDate))).map(r=>`<article class="data-card"><div><h4>${esc(r.fullName)} · ${esc(r.absenceDate)}</h4><div class="record-meta"><span>${esc(r.level)}</span><span>${esc(r.semester)}</span><span>${esc(r.reason)}</span></div><p><b>Student ID:</b> ${esc(r.studentId)}</p>${r.otherReason?`<p>${esc(r.otherReason)}</p>`:''}</div><div class="data-card-actions"><button class="button danger" data-delete-absence="${esc(r.id)}">Delete</button></div></article>`).join(''):'<div class="empty-panel">No student absences recorded yet.</div>';list.querySelectorAll('[data-delete-absence]').forEach(button=>button.onclick=()=>removeStudentRecord('studentAbsences',button.dataset.deleteAbsence))}
function saveStudentAbsence(e){e.preventDefault();const f=new FormData(e.target);records.studentAbsences.push({id:String(Date.now()),level:f.get('absenceLevel'),semester:f.get('absenceSemester'),studentId:String(f.get('studentId')).trim(),fullName:String(f.get('fullName')).trim(),absenceDate:f.get('absenceDate'),reason:f.get('reason'),otherReason:String(f.get('otherReason')||'').trim()});saveRecords();renderStudentAbsences();toast('Student absence saved')}

function refreshTeacherDirectory(){TEACHERS=unique(records.teachers);optionize($('#teacherSearchList'),TEACHERS);optionize($('#professorList'),TEACHERS)}
function renderTeachers(){const view=$('#teachersView');view.innerHTML=`<div class="page-heading"><div><span class="eyebrow">Faculty directory</span><h2>Teachers</h2><p>Manage the teacher names used by the overall timetable.</p></div><div class="heading-actions"><button class="button export-excel" id="exportTeachersExcel"><span>▦</span> Excel</button><button class="button export-pdf" id="exportTeachersPdf"><span>PDF</span> PDF</button></div></div><div class="management-grid"><form id="teacherDirectoryForm" class="panel form-panel stack"><h3 id="teacherFormTitle">Add teacher</h3><input type="hidden" name="originalName" /><div class="field"><label>Teacher name</label><input name="teacherName" required placeholder="First & Last Name" /></div><p class="form-help">Renaming a teacher also updates all of their timetable sessions.</p><div class="form-row"><button class="button secondary" type="button" id="cancelTeacherEdit">Clear</button><button class="button primary" type="submit">Save teacher</button></div></form><div class="panel data-list teacher-directory-list"><h3>Teacher directory <span class="record-count">(${TEACHERS.length})</span></h3><div id="teacherDirectoryList"></div></div></div>`;const form=$('#teacherDirectoryForm');$('#exportTeachersExcel').onclick=()=>exportOrganizedList('Teacher Directory',teacherExportRows(),'teacher-directory','excel');$('#exportTeachersPdf').onclick=()=>exportOrganizedList('Teacher Directory',teacherExportRows(),'teacher-directory','pdf');form.onsubmit=saveTeacher;$('#cancelTeacherEdit').onclick=()=>{form.reset();form.elements.originalName.value='';$('#teacherFormTitle').textContent='Add teacher'};const list=$('#teacherDirectoryList');list.innerHTML=TEACHERS.length?TEACHERS.map(name=>`<article class="data-card"><div><h4>${esc(name)}</h4><p>${sessions.filter(s=>s.professor===name).length} timetable session(s)</p></div><div class="data-card-actions"><button class="button secondary" data-edit-teacher="${esc(name)}">Edit</button><button class="button danger" data-delete-teacher="${esc(name)}">Delete</button></div></article>`).join(''):'<div class="empty-panel">No teachers in the directory.</div>';list.querySelectorAll('[data-edit-teacher]').forEach(button=>button.onclick=()=>{form.elements.originalName.value=button.dataset.editTeacher;form.elements.teacherName.value=button.dataset.editTeacher;$('#teacherFormTitle').textContent='Edit teacher';form.elements.teacherName.focus()});list.querySelectorAll('[data-delete-teacher]').forEach(button=>button.onclick=()=>deleteTeacher(button.dataset.deleteTeacher))}
function saveTeacher(e){e.preventDefault();const form=e.target,name=form.elements.teacherName.value.trim(),original=form.elements.originalName.value;if(!name)return;if(TEACHERS.some(teacher=>teacher.toLowerCase()===name.toLowerCase()&&teacher!==original)){toast('A teacher with this name already exists');return}if(original){records.teachers=records.teachers.map(teacher=>teacher===original?name:teacher);sessions.forEach(session=>{if(session.professor===original)session.professor=name});saveSchedule()}else records.teachers.push(name);saveRecords();refreshTeacherDirectory();renderTeachers();toast(original?'Teacher updated':'Teacher added')}
function deleteTeacher(name){const assigned=sessions.filter(session=>session.professor===name).length;if(assigned){alert(`This teacher cannot be deleted because ${assigned} timetable session(s) are assigned to them. Edit those sessions or rename the teacher first.`);return}if(!confirm(`Delete ${name} from the teacher directory?`))return;records.teachers=records.teachers.filter(teacher=>teacher!==name);saveRecords();refreshTeacherDirectory();renderTeachers();toast('Teacher deleted')}
function recordViewTemplate(kind,title,subtitle){return `<div class="page-heading"><div><span class="eyebrow">Official records</span><h2>${title}</h2><p>${subtitle}</p></div></div><div class="record-layout"><form class="panel form-panel stack" data-record-form="${kind}"><h3>Add meeting minutes</h3><div class="field"><label>Meeting number</label><input name="number" required placeholder="e.g. 04/2026" /></div><div class="field"><label>Committee president</label><input name="president" required placeholder="Full name" /></div><div class="field"><label>Academic level</label><select name="level" required>${LEVELS.map(level=>`<option>${esc(level)}</option>`).join('')}</select></div><div class="field"><label>Semester</label><select name="semester" required></select></div><div class="field"><label>Meeting date</label><input name="date" type="date" required /></div><div class="field"><label>Minutes file (.pdf or .doc)</label><input name="minutes" type="file" accept=".pdf,.doc,.docx" required /></div><button class="button primary" type="submit">Save meeting record</button></form><div class="panel record-list"><h3>Saved records</h3><div data-record-list="${kind}"></div></div></div>`}
function renderRecords(kind){const title=kind==='coordination'?'Pedagogical Coordination Committees':'Scientific Committee',sub=kind==='coordination'?'Archive coordination meeting minutes, presidents, levels and semesters.':'Archive scientific committee meeting minutes, presidents, levels and semesters.';const view=$(`#${kind}View`);view.innerHTML=recordViewTemplate(kind,title,sub);const form=view.querySelector('form'),level=form.elements.level,semester=form.elements.semester;const refreshMeetingSemesters=()=>optionize(semester,SEMESTERS[level.value]);level.onchange=refreshMeetingSemesters;refreshMeetingSemesters();form.onsubmit=e=>saveMeeting(e,kind);const list=view.querySelector('[data-record-list]');list.innerHTML=records[kind].length?records[kind].slice().reverse().map(r=>`<article class="record-card"><div><h4>Meeting ${esc(r.number)}</h4><p>${esc(r.date)}</p><div class="record-meta"><span>President: ${esc(r.president||'Not specified')}</span><span>${esc(r.level||'Level not specified')}</span><span>${esc(r.semester||'Semester not specified')}</span></div>${r.file?`<a class="file-link" href="#" data-file="${r.file.key}" data-name="${esc(r.file.name)}">↓ ${esc(r.file.name)}</a>`:''}</div><button class="button secondary" onclick="removeRecord('${kind}','${r.id}')">Delete</button></article>`).join(''):'<div class="empty-panel">No meeting records saved yet.</div>'}
async function saveMeeting(e,kind){e.preventDefault();const f=new FormData(e.target),id=String(Date.now()),file=await putFile(`${kind}-${id}-minutes`,f.get('minutes'));records[kind].push({id,number:f.get('number'),president:f.get('president'),level:f.get('level'),semester:f.get('semester'),date:f.get('date'),file});saveRecords();renderRecords(kind);toast('Meeting record saved')}
window.removeRecord=(kind,id)=>{if(confirm('Delete this record?')){records[kind]=records[kind].filter(r=>r.id!==id);saveRecords();kind==='competition'?renderCompetition():renderRecords(kind);toast('Record deleted')}};
function renderCompetition(){const view=$('#competitionView');view.innerHTML=`<div class="page-heading"><div><span class="eyebrow">Admissions</span><h2>Second Cycle Admission Competition</h2><p>Keep meeting documents, results and category lists together.</p></div></div><div class="competition-grid"><form id="competitionForm" class="panel form-panel stack"><h3>Add competition record</h3><div class="field"><label>Meeting date</label><input name="date" type="date" required /></div><div class="field"><label>Meeting minutes (.pdf or .doc)</label><input name="minutes" type="file" accept=".pdf,.doc,.docx" required /></div><div class="field"><label>Competition results (.pdf or .doc)</label><input name="results" type="file" accept=".pdf,.doc,.docx" required /></div><div class="field"><label>80% student list</label><input name="list80" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx" required /></div><div class="field"><label>20% student list</label><input name="list20" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx" required /></div><button class="button primary">Save competition record</button></form><div class="panel record-list"><h3>Competition archive</h3><div id="competitionList"></div></div></div>`;$('#competitionForm').onsubmit=saveCompetition;$('#competitionList').innerHTML=records.competition.length?records.competition.slice().reverse().map(r=>`<article class="record-card"><div><h4>Competition record · ${esc(r.date)}</h4>${['minutes','results','list80','list20'].map(k=>r[k]?`<p><a class="file-link" href="#" data-file="${r[k].key}" data-name="${esc(r[k].name)}">↓ ${esc(r[k].name)}</a></p>`:'').join('')}</div><button class="button secondary" onclick="removeRecord('competition','${r.id}')">Delete</button></article>`).join(''):'<div class="empty-panel">No competition records saved yet.</div>'}
async function saveCompetition(e){e.preventDefault();const f=new FormData(e.target),id=String(Date.now()),r={id,date:f.get('date')};for(const k of ['minutes','results','list80','list20'])r[k]=await putFile(`competition-${id}-${k}`,f.get(k));records.competition.push(r);saveRecords();renderCompetition();toast('Competition record saved')}

async function initializePlatform(){const status=$('#storageStatus');let needsInitialState=false;try{const response=await fetch(apiUrl('api/state'),{cache:'no-store'});if(!response.ok)throw new Error('No server storage');const state=await response.json();serverMode=true;if(state.dataVersion===DATA_VERSION&&Array.isArray(state.sessions))sessions=state.sessions;else needsInitialState=true;if(state.records)records=state.records;status.innerHTML='<b>Persistent server storage</b><span>Edits and uploads save automatically to the storage folder.</span>'}catch(e){serverMode=false;status.innerHTML='<b>Browser storage mode</b><span>Run start-platform.bat to save changes directly to files.</span>'}normalizeExtendedRecords();saveSchedule();saveRecords();if(serverMode&&needsInitialState)await fetch(apiUrl('api/state'),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataVersion:DATA_VERSION,sessions,records,updatedAt:new Date().toISOString()})});initFilters();setupEditor();refreshAudience();renderSchedule();renderRecords('coordination');renderRecords('scientific');renderCompetition();switchView(viewFromLocation(),{updateUrl:true,replace:true})}
consumeStructuredLoginRedirect();
initializePlatform();
